# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62126182571d86e0c4cb98d8139098c1ea967d86fd1e1ea2e587ef731de1dcac877053636919813c8083b2b8892d23ec9b8f7eda5e9b28f4dc50017acb55b6b

test:
  secret_key_base: d6e85b73c4fe671899ff1a351b72726def7d4fe083e34adfd8c8bb50c0dad61cdcb703ccab549a6f99ef90529d4622c12a9560904c7dd9671616899ee675d38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
